### ISSUE TITLE
Extension is crashing albert with symbol lookup error: undefined symbol 

### ISSUE THREAD

**Issue by gbdlin** [jbwong05/Extra-KDE-Settings#1]
On one of my systems, the extension is crashing Albert when I try to type in anything in albert winow. Error message on crash:

> albert: symbol lookup error: /usr/lib/albert/plugins/libextrakdesettings.so: undefined symbol: _ZN4Core12StandardItemC1E7QStringS1_S1_S1_S1_NS_4Item7UrgencyESt6vectorISt10shared_ptrINS_6ActionEESaIS7_EE

My system is ubuntu 20.10, I've installed albert from official albert repository for ubuntu 20.10: http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_20.10/, I've compiled extension without albert sources.

On my other machine everything works fine, I haven't found any noticeable, relevant difference between two systems, but I don't really know where to look for ones relevant to the case. One major difference is: the system on which the plugin fails is a fresh install of Kubuntu with almost no extra packages installed, the one on which everything works fine was upgraded through several Kubuntu releases, so it may have a lot of leftovers here and there.

**Comment by jbwong05** [comment]
Interesting. The latest version of Kubuntu I've tested on 20.04.1. Never got the change to test on Kubuntu 20.10. Not exactly sure what could be the issue, but I'll try to look into it when I get the chance.

**Comment by jbwong05** [comment]
Issue has been identified. A fix should be coming soon, hopefully by the end of the week.

**Comment by gbdlin** [comment]
If that helps in anything (don't think so as you said you've identified the problem already), I've found that on my other machine albert version was stuck on 0.16.1, after upgrading it to the newest one, it also crashes. I assume the problem is caused by some API changes in Albert. For now, I'll rollback to 0.16.4 albert version, as this one should work fine IMO.

**Comment by jbwong05** [comment]
Fix has been pushed. The latest version on the master branch should not crash on Albert v0.17.2. Closing this issue for now
